import type { Settings } from './types';

export const DEFAULT_SETTINGS: Settings = {
  paperType: 'dot-grid',
  pageSize: 'A4',
  unit: 'mm',
  dotSpacing: 5,
  dotSize: 2,
  dotOpacity: 0.5,
  gridSize: 5,
  lineWeight: 0.5,
  gridColor: 'gray',
  useCustomColor: false,
  customColor: '#000000',
  lineHeight: 7.1,
  showMargin: true,
  stavesPerPage: 10,
  batchPaperTypes: [],
  hexSize: 25.4,
  stitchWidth: 5,
  stitchHeight: 7.5,
  calligraphyAngle: 55,
  showHandwritingSlant: false,
  genkoyoushiSize: 10,
  showRulers: false,
  backgroundColor: '#ffffff',
  useCustomBackground: false,
  perspectiveType: '1-point',
  comicLayout: '2x3',
  storyboardCols: 3,
  storyboardRows: 2,
};
