import type { CategoryEntry } from './types';

const previewImage = '/previews/freegridpaper-preview.svg';
const socialImage = '/og/freegridpaper-og.svg';

export const categories: CategoryEntry[] = [
  {
    kind: 'category',
    id: 'graph-and-grid-paper',
    slug: 'graph-and-grid-paper',
    path: '/category/graph-and-grid-paper',
    canonicalPath: '/category/graph-and-grid-paper',
    indexable: true,
    title: 'Graph and Grid Paper Templates | FreeGridPaper',
    description: 'Browse printable graph paper, engineering paper, poster grids, and exact-measurement grid presets.',
    h1: 'Graph and Grid Paper',
    summary: 'Square grid templates for math, engineering, charting, mapping, and large-format planning.',
    previewImage,
    socialImage,
    templateIds: ['graph-paper', 'engineering', 'poster-size'],
    relatedCategoryIds: ['dot-and-drawing-grids', 'gaming-and-hex-grids', 'writing-and-handwriting-paper'],
    relatedGuideIds: ['graph-paper-sizes-explained', 'how-to-print-at-actual-size'],
    body: [
      { heading: 'Choose the right grid', body: 'Use smaller grids for calculations and notes, larger grids for diagrams, and poster sizes when the page needs to be read from a distance.' },
    ],
    faqs: [
      { question: 'What grid spacing should I print?', answer: '5 mm and 1/4 inch are the most common everyday graph-paper spacings.' },
    ],
  },
  {
    kind: 'category',
    id: 'dot-and-drawing-grids',
    slug: 'dot-and-drawing-grids',
    path: '/category/dot-and-drawing-grids',
    canonicalPath: '/category/dot-and-drawing-grids',
    indexable: true,
    title: 'Dot and Drawing Grid Templates | FreeGridPaper',
    description: 'Find dot grid, isometric dot, and drawing-grid paper for journaling, sketching, and design.',
    h1: 'Dot and Drawing Grids',
    summary: 'Lightweight guide patterns for sketching, journaling, wireframes, and 3D drawing.',
    previewImage,
    socialImage,
    templateIds: ['dot-grid', 'isometric-dots'],
    relatedCategoryIds: ['graph-and-grid-paper', 'art-and-storyboarding'],
    relatedGuideIds: ['best-dot-grid-spacing-for-bullet-journaling'],
    body: [
      { heading: 'Subtle structure', body: 'Dot patterns give visual alignment without heavy lines, which makes them useful for both writing and drawing.' },
    ],
  },
  {
    kind: 'category',
    id: 'writing-and-handwriting-paper',
    slug: 'writing-and-handwriting-paper',
    path: '/category/writing-and-handwriting-paper',
    canonicalPath: '/category/writing-and-handwriting-paper',
    indexable: true,
    title: 'Writing and Handwriting Paper Templates | FreeGridPaper',
    description: 'Print lined paper, checklist paper, handwriting guides, calligraphy sheets, and genkoyoushi paper.',
    h1: 'Writing and Handwriting Paper',
    summary: 'Printable writing guides for schoolwork, lists, practice sheets, and penmanship.',
    previewImage,
    socialImage,
    templateIds: ['lined-paper', 'checklist', 'handwriting', 'calligraphy', 'genkoyoushi'],
    relatedCategoryIds: ['graph-and-grid-paper', 'craft-and-pattern-paper'],
    relatedGuideIds: ['handwriting-paper-by-grade-level', 'how-to-print-at-actual-size'],
    body: [
      { heading: 'Writing support', body: 'Choose ruled spacing for general writing, handwriting guides for learners, or specialty sheets for scripts and composition practice.' },
    ],
  },
  {
    kind: 'category',
    id: 'music-paper',
    slug: 'music-paper',
    path: '/category/music-paper',
    canonicalPath: '/category/music-paper',
    indexable: true,
    title: 'Printable Music Paper Templates | FreeGridPaper',
    description: 'Create blank sheet music, guitar tablature, and bass tablature PDFs.',
    h1: 'Music Paper',
    summary: 'Staff and tablature paper for composition, lessons, transcription, and practice.',
    previewImage,
    socialImage,
    templateIds: ['music-staff', 'guitar-tab', 'bass-tab'],
    relatedCategoryIds: ['writing-and-handwriting-paper'],
    relatedGuideIds: ['music-staff-spacing-guide'],
    body: [
      { heading: 'Music notation', body: 'Use staff paper for notation and tablature pages when the instrument-specific line layout matters.' },
    ],
  },
  {
    kind: 'category',
    id: 'gaming-and-hex-grids',
    slug: 'gaming-and-hex-grids',
    path: '/category/gaming-and-hex-grids',
    canonicalPath: '/category/gaming-and-hex-grids',
    indexable: true,
    title: 'Gaming and Hex Grid Paper | FreeGridPaper',
    description: 'Print hex grids and large-format map paper for tabletop games, D&D, strategy maps, and campaign planning.',
    h1: 'Gaming and Hex Grids',
    summary: 'Hex and map-oriented templates for tabletop games, battle maps, and strategy layouts.',
    previewImage,
    socialImage,
    templateIds: ['hex-grid', 'poster-hex'],
    relatedCategoryIds: ['graph-and-grid-paper', 'art-and-storyboarding'],
    relatedGuideIds: ['how-to-choose-hex-size-for-dnd-maps'],
    body: [
      { heading: 'Map scale', body: 'Hex size controls how the map works at the table. One-inch hexes are the default for most miniatures.' },
    ],
  },
  {
    kind: 'category',
    id: 'art-and-storyboarding',
    slug: 'art-and-storyboarding',
    path: '/category/art-and-storyboarding',
    canonicalPath: '/category/art-and-storyboarding',
    indexable: true,
    title: 'Art and Storyboarding Templates | FreeGridPaper',
    description: 'Browse printable perspective grids, comic page layouts, storyboard templates, and drawing aids.',
    h1: 'Art and Storyboarding',
    summary: 'Drawing templates for perspective, panel layouts, visual planning, and sequential art.',
    previewImage,
    socialImage,
    templateIds: ['perspective-grid', 'perspective-grid-2', 'comic-layout', 'storyboard'],
    relatedCategoryIds: ['dot-and-drawing-grids', 'gaming-and-hex-grids'],
    relatedGuideIds: [],
    body: [
      { heading: 'Plan the page', body: 'These templates help artists frame scenes, establish perspective, and block page structure before final drawing.' },
    ],
  },
  {
    kind: 'category',
    id: 'craft-and-pattern-paper',
    slug: 'craft-and-pattern-paper',
    path: '/category/craft-and-pattern-paper',
    canonicalPath: '/category/craft-and-pattern-paper',
    indexable: true,
    title: 'Craft and Pattern Paper Templates | FreeGridPaper',
    description: 'Create printable pattern paper for knitting, cross-stitch, fiber arts, and gauge-aware design.',
    h1: 'Craft and Pattern Paper',
    summary: 'Pattern-planning paper for fiber arts and gauge-aware craft designs.',
    previewImage,
    socialImage,
    templateIds: ['knitting'],
    relatedCategoryIds: ['graph-and-grid-paper', 'writing-and-handwriting-paper'],
    relatedGuideIds: [],
    body: [
      { heading: 'Match the material', body: 'Rectangular grids can better match real stitch proportions than ordinary square graph paper.' },
    ],
  },
];
