import type { SitePageEntry } from './types';
import { templates } from './templates';

const previewImage = '/previews/freegridpaper-preview.svg';
const socialImage = '/og/freegridpaper-og.svg';

export const sitePages: SitePageEntry[] = [
  {
    kind: 'site',
    id: 'home',
    slug: '',
    path: '/',
    canonicalPath: '/',
    indexable: true,
    title: 'FreeGridPaper - Free Printable Grid Paper Generator',
    description: 'Generate custom printable grid paper, dot grids, lined paper, music staves, and specialty stationery instantly as vector PDFs.',
    h1: 'FreeGridPaper',
    summary: 'Create print-ready stationery PDFs directly in your browser.',
    previewImage,
    socialImage,
    body: [{ heading: 'Print-ready paper', body: 'FreeGridPaper creates crisp vector PDFs for graph paper, dot grids, writing paper, music paper, and specialty layouts.' }],
  },
  {
    kind: 'site',
    id: 'templates',
    slug: 'templates',
    path: '/templates',
    canonicalPath: '/templates',
    indexable: true,
    title: 'Printable Paper Templates | FreeGridPaper',
    description: 'Browse every FreeGridPaper template, including graph paper, dot grids, hex grids, lined paper, music paper, and drawing guides.',
    h1: 'Printable Paper Templates',
    summary: 'Browse every printable paper generator by category.',
    previewImage,
    socialImage,
    body: [{ heading: 'Template library', body: 'Choose a template, customize the settings, and download a crisp vector PDF.' }],
  },
  {
    kind: 'site',
    id: 'faq',
    slug: 'faq',
    path: '/faq',
    canonicalPath: '/faq',
    indexable: true,
    title: 'Frequently Asked Questions | FreeGridPaper',
    description: 'Answers to common questions about creating, customizing, downloading, and printing FreeGridPaper PDFs.',
    h1: 'Frequently Asked Questions',
    summary: 'Help for generating and printing paper templates correctly.',
    previewImage,
    socialImage,
    faqs: [
      {
        question: 'How do I generate and download a PDF?',
        answer: "Use a quick download preset or customize your paper type, size, and settings, then click Download PDF. The PDF is generated instantly in your browser.",
      },
      {
        question: 'What paper types are available?',
        answer: `FreeGridPaper includes ${templates.length} current printable templates, including graph paper, dot grids, isometric dots, hex grids, lined paper, handwriting guides, music staff paper, guitar tab, bass tab, checklist paper, calligraphy guides, genkoyoushi, perspective grids, comic layouts, storyboards, engineering paper, and large-format poster options.`,
      },
      {
        question: 'How do I print the PDF correctly?',
        answer: "Set Page Scaling or Scale to 100% or Actual Size, disable Shrink to Fit, and use minimum margins when exact grid measurements matter.",
      },
    ],
    body: [],
  },
  {
    kind: 'site',
    id: 'about',
    slug: 'about',
    path: '/about',
    canonicalPath: '/about',
    indexable: true,
    title: 'About FreeGridPaper',
    description: 'Learn about FreeGridPaper, a browser-based tool for printable vector PDF stationery.',
    h1: 'About FreeGridPaper',
    summary: 'FreeGridPaper is built for fast, private, print-ready stationery generation.',
    previewImage,
    socialImage,
    body: [{ heading: 'Built for printing', body: 'The tool focuses on accurate spacing, crisp vector output, and practical templates that work from a browser.' }],
  },
  {
    kind: 'site',
    id: 'contact',
    slug: 'contact',
    path: '/contact',
    canonicalPath: '/contact',
    indexable: true,
    title: 'Contact FreeGridPaper',
    description: 'Contact FreeGridPaper for questions, corrections, and template suggestions.',
    h1: 'Contact',
    summary: 'Send questions, corrections, and template suggestions for FreeGridPaper.',
    previewImage,
    socialImage,
    body: [{ heading: 'Get in touch', body: 'For questions, corrections, or template ideas, contact Ellie Petal Media through the published contact channels for this site.' }],
  },
  {
    kind: 'site',
    id: 'privacy',
    slug: 'privacy',
    path: '/privacy',
    canonicalPath: '/privacy',
    indexable: true,
    title: 'Privacy Policy | FreeGridPaper',
    description: 'Privacy information for FreeGridPaper and its browser-based PDF generator.',
    h1: 'Privacy Policy',
    summary: 'FreeGridPaper generates PDFs in your browser and stores custom settings locally on your device.',
    previewImage,
    socialImage,
    body: [{ heading: 'Browser-based generation', body: 'Your paper settings are used locally to render previews and PDFs. Saved settings use browser storage on your device.' }],
  },
];
