import type { TemplateEntry } from './types';

const previewImage = '/previews/freegridpaper-preview.svg';
const socialImage = '/og/freegridpaper-og.svg';

export const templates: TemplateEntry[] = ([
  {
    kind: 'template',
    id: 'graph-paper',
    slug: 'graph-paper',
    path: '/graph',
    canonicalPath: '/graph',
    indexable: true,
    label: 'Graph Paper',
    categoryId: 'graph-and-grid-paper',
    title: 'Standard Graph Paper | FreeGridPaper',
    description: 'Create and download custom graph paper PDFs with exact grid spacing, line color, and vector output.',
    h1: 'Standard Graph Paper',
    summary: 'Printable square grid paper for math, drafting, charts, mapping, and pixel art.',
    quickDownloadText: 'Graph Paper (Letter)',
    previewImage,
    socialImage,
    settings: { paperType: 'graph-paper', pageSize: 'Letter' },
    relatedTemplateIds: ['dot-grid', 'isometric-dots', 'hex-grid'],
    popularPresetIds: ['quarter-inch-graph-paper', 'one-centimeter-graph-paper', 'five-mm-graph-paper'],
    body: [
      { heading: 'Best uses', body: 'Graph paper works for measured drawing, school math, engineering sketches, charts, and game maps.', items: ['Use 5 mm or 1/4 inch spacing for general notes.', 'Use darker lines for scanning or high-contrast worksheets.', 'Use larger sheets for posters and wall maps.'] },
      { heading: 'Print tip', body: 'Print at Actual Size or 100% scale so each square matches the selected measurement.' },
    ],
  },
  {
    kind: 'template',
    id: 'dot-grid',
    slug: 'dot-grid-paper',
    path: '/dot-grid',
    canonicalPath: '/dot-grid',
    indexable: true,
    label: 'Dot Grid',
    categoryId: 'dot-and-drawing-grids',
    title: 'Dot Grid Paper | FreeGridPaper',
    description: 'Download printable dot grid paper with adjustable dot spacing, size, and opacity.',
    h1: 'Dot Grid Paper',
    summary: 'A subtle dotted layout for bullet journals, planning, sketching, and design notes.',
    quickDownloadText: 'Dot Grid (A4)',
    previewImage,
    socialImage,
    settings: { paperType: 'dot-grid', pageSize: 'A4' },
    relatedTemplateIds: ['graph-paper', 'isometric-dots', 'lined-paper'],
    popularPresetIds: ['a4-dot-grid-paper', 'letter-dot-grid-paper'],
    body: [
      { heading: 'Best uses', body: 'Dot grid paper gives structure without the visual weight of full grid lines.', items: ['Bullet journaling', 'Wireframes', 'Lettering practice'] },
      { heading: 'Print tip', body: 'Lower opacity keeps dots visible as guides without overpowering handwriting or sketches.' },
    ],
  },
  {
    kind: 'template',
    id: 'hex-grid',
    slug: 'hex-grid-paper',
    path: '/hex-paper',
    canonicalPath: '/hex-paper',
    indexable: true,
    label: 'Hexagon Grid',
    categoryId: 'gaming-and-hex-grids',
    title: 'Free Printable Hex Grid Paper | FreeGridPaper',
    description: 'Generate hexagon grid paper PDFs for D&D maps, wargaming, chemistry, quilting, and strategy design.',
    h1: 'Hex Grid Paper',
    summary: 'Honeycomb grid paper with adjustable hex size for gaming, maps, chemistry, and craft work.',
    quickDownloadText: 'Hex Grid (Letter, 1")',
    previewImage,
    socialImage,
    settings: { paperType: 'hex-grid', pageSize: 'Letter', hexSize: 25.4 },
    relatedTemplateIds: ['graph-paper', 'isometric-dots', 'storyboard'],
    popularPresetIds: ['one-inch-hex-grid-paper', 'three-quarter-inch-hex-grid-paper'],
    body: [
      { heading: 'Best uses', body: 'Hex paper is useful whenever adjacency and movement matter.', items: ['Tabletop battle maps', 'Organic chemistry structures', 'Strategy and board-game prototypes'] },
      { heading: 'Print tip', body: 'Use 1 inch hexes for most tabletop miniatures and print large maps on Arch D or Arch E paper.' },
    ],
  },
  {
    kind: 'template',
    id: 'music-staff',
    slug: 'music-staff-paper',
    path: '/music-staff',
    canonicalPath: '/music-staff',
    indexable: true,
    label: 'Music Staff',
    categoryId: 'music-paper',
    title: 'Blank Sheet Music PDF | FreeGridPaper',
    description: 'Create blank sheet music PDFs with adjustable staves per page and crisp vector staff lines.',
    h1: 'Blank Sheet Music',
    summary: 'Printable staff paper for composition, theory homework, transcription, and lessons.',
    quickDownloadText: 'Blank Sheet Music (A4)',
    previewImage,
    socialImage,
    settings: { paperType: 'music-staff', pageSize: 'A4' },
    relatedTemplateIds: ['guitar-tab', 'bass-tab'],
    popularPresetIds: ['blank-sheet-music-10-staves'],
    body: [
      { heading: 'Best uses', body: 'Blank staff paper supports composition, ear training, transcription, and classroom theory work.' },
      { heading: 'Print tip', body: 'Use fewer staves per page when you need room for lyrics, fingering, or teacher notes.' },
    ],
  },
  {
    kind: 'template',
    id: 'engineering',
    slug: 'engineering-graph-paper',
    path: '/engineering',
    canonicalPath: '/engineering',
    indexable: true,
    label: 'Engineering Paper',
    categoryId: 'graph-and-grid-paper',
    title: 'Engineering Graph Paper | FreeGridPaper',
    description: 'Create engineering-style graph paper with green grid lines and a light yellow background.',
    h1: 'Engineering Graph Paper',
    summary: 'A classic engineering paper effect with a green grid on a yellow background.',
    quickDownloadText: 'Engineering Paper',
    previewImage,
    socialImage,
    settings: { paperType: 'graph-paper', useCustomColor: true, customColor: '#228B22', backgroundColor: '#FFFFC5', useCustomBackground: true },
    relatedTemplateIds: ['graph-paper', 'lined-paper'],
    popularPresetIds: ['five-mm-graph-paper'],
    body: [
      { heading: 'Best uses', body: 'Engineering paper is useful for calculations, diagrams, technical notes, and marked-up design work.' },
      { heading: 'Print tip', body: 'Use a lighter line weight when printing on colored backgrounds to preserve readability.' },
    ],
  },
  {
    kind: 'template',
    id: 'poster-size',
    slug: 'poster-size-grid-paper',
    path: '/poster-size',
    canonicalPath: '/poster-size',
    indexable: true,
    label: 'Poster Size Grid',
    categoryId: 'graph-and-grid-paper',
    title: 'Poster Size Grid Paper | FreeGridPaper',
    description: 'Generate large-format poster graph paper PDFs for wall charts, classrooms, maps, and planning.',
    h1: 'Poster Size Graph',
    summary: 'Large-format graph paper for posters, wall planning, classroom visuals, and oversized maps.',
    quickDownloadText: 'Poster Graph (24x36")',
    previewImage,
    socialImage,
    settings: { paperType: 'graph-paper', pageSize: 'ArchD' },
    relatedTemplateIds: ['graph-paper', 'hex-grid'],
    popularPresetIds: ['quarter-inch-graph-paper'],
    body: [
      { heading: 'Best uses', body: 'Poster-size grids help with wall displays, mapping, workshop planning, and classroom demonstrations.' },
      { heading: 'Print tip', body: 'Confirm your print shop supports the selected architectural sheet size before exporting.' },
    ],
  },
  {
    kind: 'template',
    id: 'poster-hex',
    slug: 'poster-size-hex-paper',
    path: '/poster-hex',
    canonicalPath: '/poster-hex',
    indexable: true,
    label: 'Poster Hex Grid',
    categoryId: 'gaming-and-hex-grids',
    title: 'Poster Size Hex Grid for D&D | FreeGridPaper',
    description: 'Create poster-size hex grid PDFs for tabletop battle maps and large strategy layouts.',
    h1: 'Poster Size Hex',
    summary: 'Large-format hex paper for tabletop maps, campaigns, and strategy boards.',
    quickDownloadText: 'Poster Hex Grid (24x36", 1")',
    previewImage,
    socialImage,
    settings: { paperType: 'hex-grid', pageSize: 'ArchD', hexSize: 25.4 },
    relatedTemplateIds: ['hex-grid', 'storyboard'],
    popularPresetIds: ['one-inch-hex-grid-paper'],
    body: [
      { heading: 'Best uses', body: 'Poster hex grids are sized for encounter maps, regional planning, and large tabletop scenes.' },
      { heading: 'Print tip', body: 'Use 1 inch hexes when the map needs to work with standard miniatures.' },
    ],
  },
  {
    kind: 'template',
    id: 'calligraphy',
    slug: 'calligraphy-practice-paper',
    path: '/calligraphy',
    canonicalPath: '/calligraphy',
    indexable: true,
    label: 'Calligraphy',
    categoryId: 'writing-and-handwriting-paper',
    title: 'Calligraphy Practice Paper | FreeGridPaper',
    description: 'Generate calligraphy guide sheets with horizontal baselines and adjustable slant guides.',
    h1: 'Calligraphy Practice Paper',
    summary: 'Practice sheets with baselines and angled guides for script lettering.',
    quickDownloadText: 'Calligraphy Paper',
    previewImage,
    socialImage,
    settings: { paperType: 'calligraphy' },
    relatedTemplateIds: ['handwriting', 'lined-paper'],
    popularPresetIds: [],
    body: [
      { heading: 'Best uses', body: 'Calligraphy guides help keep x-height, baseline, and slant consistent across a page.' },
      { heading: 'Print tip', body: 'Choose a slant angle that matches the script style you are practicing.' },
    ],
  },
  {
    kind: 'template',
    id: 'knitting',
    slug: 'knitting-graph-paper',
    path: '/knitting',
    canonicalPath: '/knitting',
    indexable: true,
    label: 'Knitting Graph',
    categoryId: 'craft-and-pattern-paper',
    title: 'Knitting & Cross-Stitch Graph Paper | FreeGridPaper',
    description: 'Create knitting and cross-stitch graph paper with rectangular cells that match your gauge.',
    h1: 'Knitting Graph Paper',
    summary: 'Adjustable rectangular graph paper for knitting, cross-stitch, and craft pattern design.',
    quickDownloadText: 'Knitting Graph',
    previewImage,
    socialImage,
    settings: { paperType: 'knitting' },
    relatedTemplateIds: ['graph-paper'],
    popularPresetIds: [],
    body: [
      { heading: 'Best uses', body: 'Gauge-aware grids help pattern drawings match the shape of finished stitches.' },
      { heading: 'Print tip', body: 'Measure a swatch first, then set stitch width and height to match your real gauge.' },
    ],
  },
  {
    kind: 'template',
    id: 'handwriting',
    slug: 'handwriting-practice-paper',
    path: '/handwriting',
    canonicalPath: '/handwriting',
    indexable: true,
    label: 'Handwriting',
    categoryId: 'writing-and-handwriting-paper',
    title: 'Handwriting Practice Paper | FreeGridPaper',
    description: 'Print handwriting practice paper with guide lines for letter size, spacing, and early writing practice.',
    h1: 'Handwriting Practice Paper',
    summary: 'Guided writing paper for early learners, penmanship drills, and classroom practice.',
    quickDownloadText: 'Handwriting Paper (Letter)',
    previewImage,
    socialImage,
    settings: { paperType: 'handwriting', pageSize: 'Letter', lineHeight: 15 },
    relatedTemplateIds: ['lined-paper', 'calligraphy'],
    popularPresetIds: ['kindergarten-handwriting-paper'],
    body: [
      { heading: 'Best uses', body: 'Handwriting paper helps writers practice letter height, baseline placement, and spacing.' },
      { heading: 'Print tip', body: 'Use larger line height for younger learners and smaller spacing as control improves.' },
    ],
  },
  {
    kind: 'template',
    id: 'guitar-tab',
    slug: 'guitar-tab-paper',
    path: '/guitar-tab',
    canonicalPath: '/guitar-tab',
    indexable: true,
    label: 'Guitar Tab',
    categoryId: 'music-paper',
    title: 'Guitar Tablature PDF | FreeGridPaper',
    description: 'Print blank guitar tablature paper with clean six-line staves for lessons and transcription.',
    h1: 'Guitar Tablature',
    summary: 'Six-line tablature paper for guitar teachers, students, and transcribers.',
    quickDownloadText: 'Guitar Tab (Letter)',
    previewImage,
    socialImage,
    settings: { paperType: 'guitar-tab', pageSize: 'Letter' },
    relatedTemplateIds: ['bass-tab', 'music-staff'],
    popularPresetIds: ['blank-guitar-tab-paper'],
    body: [
      { heading: 'Best uses', body: 'Guitar tab paper is useful for riffs, chord studies, solos, and lesson handouts.' },
      { heading: 'Print tip', body: 'Leave extra space between staves when adding rhythm notation or performance notes.' },
    ],
  },
  {
    kind: 'template',
    id: 'bass-tab',
    slug: 'bass-tab-paper',
    path: '/bass-tab',
    canonicalPath: '/bass-tab',
    indexable: true,
    label: 'Bass Tab',
    categoryId: 'music-paper',
    title: 'Bass Tablature PDF | FreeGridPaper',
    description: 'Print blank bass tablature paper with four-line staves for bass transcription and practice.',
    h1: 'Bass Tablature',
    summary: 'Four-line tablature paper for bass players, teachers, and transcription work.',
    quickDownloadText: 'Bass Tab (Letter)',
    previewImage,
    socialImage,
    settings: { paperType: 'bass-tab', pageSize: 'Letter' },
    relatedTemplateIds: ['guitar-tab', 'music-staff'],
    popularPresetIds: ['blank-bass-tab-paper'],
    body: [
      { heading: 'Best uses', body: 'Bass tab paper keeps four-string parts uncluttered and easy to annotate.' },
      { heading: 'Print tip', body: 'Use darker lines when the sheet will be read on a stand or in low light.' },
    ],
  },
  {
    kind: 'template',
    id: 'genkoyoushi',
    slug: 'genkoyoushi-paper',
    path: '/genkoyoushi',
    canonicalPath: '/genkoyoushi',
    indexable: true,
    label: 'Genkoyoushi',
    categoryId: 'writing-and-handwriting-paper',
    title: 'Genkoyoushi Japanese Manuscript Paper | FreeGridPaper',
    description: 'Generate genkoyoushi manuscript paper for Japanese writing practice with square character guides.',
    h1: 'Genkoyoushi Paper',
    summary: 'Japanese manuscript paper with character boxes and internal guide lines.',
    quickDownloadText: 'Genkoyoushi (A4)',
    previewImage,
    socialImage,
    settings: { paperType: 'genkoyoushi', pageSize: 'A4', genkoyoushiSize: 10 },
    relatedTemplateIds: ['graph-paper', 'handwriting'],
    popularPresetIds: [],
    body: [
      { heading: 'Best uses', body: 'Genkoyoushi paper supports kanji, kana, and composition practice with balanced character spacing.' },
      { heading: 'Print tip', body: 'Use a square size that leaves enough room for stroke order practice.' },
    ],
  },
  {
    kind: 'template',
    id: 'perspective-grid',
    slug: 'perspective-grid-paper',
    path: '/perspective-1',
    canonicalPath: '/perspective-1',
    indexable: true,
    label: 'Perspective Grid',
    categoryId: 'art-and-storyboarding',
    title: '1-Point Perspective Grid | FreeGridPaper',
    description: 'Download perspective grid paper for architectural sketching, drawing practice, and scene layout.',
    h1: '1-Point Perspective',
    summary: 'Perspective guide paper for drawing rooms, streets, objects, and architectural scenes.',
    quickDownloadText: '1-Point Perspective',
    previewImage,
    socialImage,
    settings: { paperType: 'perspective-grid', perspectiveType: '1-point' },
    relatedTemplateIds: ['isometric-dots', 'storyboard', 'comic-layout'],
    popularPresetIds: [],
    body: [
      { heading: 'Best uses', body: 'Perspective grids help align edges and vanishing points while learning spatial drawing.' },
      { heading: 'Print tip', body: 'Use lighter lines when sketching over the guide with pencil or ink.' },
    ],
  },
  {
    kind: 'template',
    id: 'perspective-grid-2',
    slug: 'two-point-perspective-grid-paper',
    path: '/perspective-2',
    canonicalPath: '/perspective-2',
    indexable: true,
    label: '2-Point Perspective',
    categoryId: 'art-and-storyboarding',
    title: '2-Point Perspective Grid | FreeGridPaper',
    description: 'Download two-point perspective grid paper for city corners, architecture, and object drawing.',
    h1: '2-Point Perspective',
    summary: 'A two-vanishing-point drawing guide for angled objects and architectural sketches.',
    quickDownloadText: '2-Point Perspective',
    previewImage,
    socialImage,
    settings: { paperType: 'perspective-grid', perspectiveType: '2-point' },
    relatedTemplateIds: ['perspective-grid', 'storyboard', 'isometric-dots'],
    popularPresetIds: [],
    body: [
      { heading: 'Best uses', body: 'Two-point perspective helps with corners, street scenes, boxes, buildings, and interior sketches.' },
      { heading: 'Print tip', body: 'Keep guide lines subtle if the page will be used under final art.' },
    ],
  },
  {
    kind: 'template',
    id: 'comic-layout',
    slug: 'comic-layout-paper',
    path: '/comic-2x3',
    canonicalPath: '/comic-2x3',
    indexable: true,
    label: 'Comic Layout',
    categoryId: 'art-and-storyboarding',
    title: 'Comic Book Template (2x3) | FreeGridPaper',
    description: 'Print comic book layout templates with clean panel grids for thumbnails, manga, and comic pages.',
    h1: 'Comic Layout (2x3)',
    summary: 'Panel templates for planning comic pages, thumbnails, manga, and graphic-novel layouts.',
    quickDownloadText: 'Comic 2x3',
    previewImage,
    socialImage,
    settings: { paperType: 'comic-layout', comicLayout: '2x3' },
    relatedTemplateIds: ['storyboard', 'perspective-grid'],
    popularPresetIds: [],
    body: [
      { heading: 'Best uses', body: 'Comic layout paper removes the measuring step so artists can focus on page rhythm and panel design.' },
      { heading: 'Print tip', body: 'Use a lighter color if the panel guides will sit under final pencil work.' },
    ],
  },
  {
    kind: 'template',
    id: 'storyboard',
    slug: 'storyboard-template',
    path: '/storyboard',
    canonicalPath: '/storyboard',
    indexable: true,
    label: 'Storyboard',
    categoryId: 'art-and-storyboarding',
    title: 'Storyboard Template | FreeGridPaper',
    description: 'Create printable storyboard templates with 16:9 frames and writing space for scene notes.',
    h1: 'Storyboard Template',
    summary: 'Printable storyboard frames for video, film, animation, and commercial planning.',
    quickDownloadText: 'Storyboard (3x2)',
    previewImage,
    socialImage,
    settings: { paperType: 'storyboard', storyboardCols: 3, storyboardRows: 2 },
    relatedTemplateIds: ['comic-layout', 'perspective-grid'],
    popularPresetIds: ['16-9-storyboard-template'],
    body: [
      { heading: 'Best uses', body: 'Storyboard templates help block camera framing, movement, dialogue, and production notes.' },
      { heading: 'Print tip', body: 'Choose fewer rows when you need more room for notes under each frame.' },
    ],
  },
  {
    kind: 'template',
    id: 'isometric-dots',
    slug: 'isometric-dot-paper',
    path: '/isometric-dots',
    canonicalPath: '/isometric-dots',
    indexable: true,
    label: 'Isometric Dots',
    categoryId: 'dot-and-drawing-grids',
    title: 'Isometric Dot Grid Paper | FreeGridPaper',
    description: 'Print isometric dot grid paper for 3D sketching, architecture, design, and game maps.',
    h1: 'Isometric Dot Grid',
    summary: 'Triangular dot spacing for isometric drawing and 3D sketching.',
    quickDownloadText: 'Isometric Dots (A4)',
    previewImage,
    socialImage,
    settings: { paperType: 'isometric-dots', pageSize: 'A4' },
    relatedTemplateIds: ['dot-grid', 'perspective-grid', 'hex-grid'],
    popularPresetIds: [],
    body: [
      { heading: 'Best uses', body: 'Isometric dots support 3D object drawing, architectural sketches, and design ideation.' },
      { heading: 'Print tip', body: 'Use small dots and moderate opacity for a guide that stays out of the way.' },
    ],
  },
  {
    kind: 'template',
    id: 'lined-paper',
    slug: 'lined-paper',
    path: '/lined-paper',
    canonicalPath: '/lined-paper',
    indexable: true,
    label: 'Lined Paper',
    categoryId: 'writing-and-handwriting-paper',
    title: 'Lined Paper PDF | FreeGridPaper',
    description: 'Generate printable lined paper with college ruled or wide ruled spacing and optional margin lines.',
    h1: 'Lined Paper',
    summary: 'Classic ruled paper for notes, schoolwork, journals, lists, and handwriting.',
    quickDownloadText: 'Lined Paper (Letter)',
    previewImage,
    socialImage,
    settings: { paperType: 'lined-paper', pageSize: 'Letter' },
    relatedTemplateIds: ['checklist', 'handwriting', 'calligraphy'],
    popularPresetIds: ['college-ruled-paper', 'wide-ruled-paper'],
    body: [
      { heading: 'Best uses', body: 'Lined paper supports everyday writing, school assignments, journals, and meeting notes.' },
      { heading: 'Print tip', body: 'College ruled spacing fits more lines; wide ruled spacing gives more room for larger handwriting.' },
    ],
  },
  {
    kind: 'template',
    id: 'checklist',
    slug: 'checklist-paper',
    path: '/checklist',
    canonicalPath: '/checklist',
    indexable: true,
    label: 'Checklist',
    categoryId: 'writing-and-handwriting-paper',
    title: 'Printable Checklist Paper | FreeGridPaper',
    description: 'Create lined checklist paper with checkbox squares for tasks, packing lists, planning, and tracking.',
    h1: 'Checklist Paper',
    summary: 'Lined task paper with checkboxes for planning, lists, inventories, and project notes.',
    quickDownloadText: 'Checklist (Letter)',
    previewImage,
    socialImage,
    settings: { paperType: 'checklist', pageSize: 'Letter' },
    relatedTemplateIds: ['lined-paper', 'dot-grid'],
    popularPresetIds: [],
    body: [
      { heading: 'Best uses', body: 'Checklist paper is useful for errands, packing, project steps, inventories, and repeatable routines.' },
      { heading: 'Print tip', body: 'Use wider spacing when list items need extra notes or descriptions.' },
    ],
  },
] as TemplateEntry[]).map((entry) => ({
  ...entry,
  previewImage: `/previews/templates/${entry.id}.svg`,
  socialImage: `/og/${entry.id}.svg`,
}));
